=== sandrolabruzzo/doiBoost/python/schema/doiBoostSchema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "10.5281/zenodo.1438356",
  "type": "object",
  "title": "The DOI Boost",
  "required": [
    "title",
    "authors",
    "issued",
    "abstract",
    "subject",
    "type",
    "license",
    "instances",
    "published-online",
    "published-print",
    "accepted",
    "publisher",
    "doi",
    "doi-url",
    "issn",
    "collected-from"
  ],
  "properties": {
    "title": {
      "$id": "#/properties/title",
      "type": "string",
      "title": "The Title",
      "default": "",
      "examples": [
        "My Title"
      ],
      "pattern": "^(.*)$"
    },
    "authors": {
      "$id": "#/properties/authors",
      "type": "array",
      "title": "The Authors",
      "items": {
        "$id": "#/properties/authors/items",
        "type": "object",
        "title": "The Items",
        "required": [
          "given",
          "family",
          "fullname",
          "identifiers",
          "affiliations"
        ],
        "properties": {
          "given": {
            "$id": "#/properties/authors/items/properties/given",
            "type": "string",
            "title": "The Given",
            "default": "",
            "examples": [
              "Marco"
            ],
            "pattern": "^(.*)$"
          },
          "family": {
            "$id": "#/properties/authors/items/properties/family",
            "type": "string",
            "title": "The Family",
            "default": "",
            "examples": [
              "Rossi"
            ],
            "pattern": "^(.*)$"
          },
          "fullname": {
            "$id": "#/properties/authors/items/properties/fullname",
            "type": "string",
            "title": "The Fullname",
            "default": "",
            "examples": [
              "Marco Rossi"
            ],
            "pattern": "^(.*)$"
          },
          "identifiers": {
            "$id": "#/properties/authors/items/properties/identifiers",
            "type": "array",
            "title": "The Identifiers",
            "items": {
              "$id": "#/properties/authors/items/properties/identifiers/items",
              "type": "object",
              "title": "The Items",
              "required": [
                "schema",
                "value",
                "provenance"
              ],
              "properties": {
                "schema": {
                  "$id": "#/properties/authors/items/properties/identifiers/items/properties/schema",
                  "type": "string",
                  "title": "The",
                  "default": "",
                  "examples": [
                    "ORCID"
                  ],
                  "pattern": "^(.*)$"
                },
                "value": {
                  "$id": "#/properties/authors/items/properties/identifiers/items/properties/value",
                  "type": "string",
                  "title": "The Value",
                  "default": "",
                  "examples": [
                    "https://..../0000-0002-3337-2025"
                  ],
                  "pattern": "^(.*)$"
                },
                "provenance": {
                  "$id": "#/properties/authors/items/properties/identifiers/items/properties/provenance",
                  "type": "string",
                  "title": "The Provenance",
                  "default": "",
                  "examples": [
                    "ORCID"
                  ],
                  "pattern": "^(.*)$"
                }
              }
            }
          },
          "affiliations": {
            "$id": "#/properties/authors/items/properties/affiliations",
            "type": "array",
            "title": "The Affiliations",
            "items": {
              "$id": "#/properties/authors/items/properties/affiliations/items",
              "type": "object",
              "title": "The Items",
              "required": [
                "value",
                "official-page",
                "identifiers",
                "provenance"
              ],
              "properties": {
                "value": {
                  "$id": "#/properties/authors/items/properties/affiliations/items/properties/value",
                  "type": "string",
                  "title": "The Value",
                  "default": "",
                  "examples": [
                    "My Affiliation Name"
                  ],
                  "pattern": "^(.*)$"
                },
                "official-page": {
                  "$id": "#/properties/authors/items/properties/affiliations/items/properties/official-page",
                  "type": "string",
                  "title": "The Official-page",
                  "default": "",
                  "examples": [
                    "www.affiliation.org"
                  ],
                  "pattern": "^(.*)$"
                },
                "identifiers": {
                  "$id": "#/properties/authors/items/properties/affiliations/items/properties/identifiers",
                  "type": "array",
                  "title": "The Identifiers",
                  "items": {
                    "$id": "#/properties/authors/items/properties/affiliations/items/properties/identifiers/items",
                    "type": "object",
                    "title": "The Items",
                    "required": [
                      "schema",
                      "value"
                    ],
                    "properties": {
                      "schema": {
                        "$id": "#/properties/authors/items/properties/affiliations/items/properties/identifiers/items/properties/schema",
                        "type": "string",
                        "title": "The",
                        "default": "",
                        "examples": [
                          "grid.ac"
                        ],
                        "pattern": "^(.*)$"
                      },
                      "value": {
                        "$id": "#/properties/authors/items/properties/affiliations/items/properties/identifiers/items/properties/value",
                        "type": "string",
                        "title": "The Value",
                        "default": "",
                        "examples": [
                          "https://.../grid.12345.a"
                        ],
                        "pattern": "^(.*)$"
                      }
                    }
                  }
                },
                "provenance": {
                  "$id": "#/properties/authors/items/properties/affiliations/items/properties/provenance",
                  "type": "string",
                  "title": "The Provenance",
                  "default": "",
                  "examples": [
                    "MAG"
                  ],
                  "pattern": "^(.*)$"
                }
              }
            }
          }
        }
      }
    },
    "issued": {
      "$id": "#/properties/issued",
      "type": "string",
      "title": "The Issued",
      "default": "",
      "examples": [
        "2016-07-01"
      ],
      "pattern": "^(.*)$"
    },
    "abstract": {
      "$id": "#/properties/abstract",
      "type": "array",
      "title": "The Abstract",
      "items": {
        "$id": "#/properties/abstract/items",
        "type": "object",
        "title": "The Items",
        "required": [
          "value",
          "provenance"
        ],
        "properties": {
          "value": {
            "$id": "#/properties/abstract/items/properties/value",
            "type": "string",
            "title": "The Value",
            "default": "",
            "examples": [
              "Abstract Text"
            ],
            "pattern": "^(.*)$"
          },
          "provenance": {
            "$id": "#/properties/abstract/items/properties/provenance",
            "type": "string",
            "title": "The Provenance",
            "default": "",
            "examples": [
              "MAG"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "subject": {
      "$id": "#/properties/subject",
      "type": "array",
      "title": "The Subject",
      "items": {
        "$id": "#/properties/subject/items",
        "type": "string",
        "title": "The Items",
        "default": "",
        "examples": [
          "Agronomy and Crop Science",
          "Forestry"
        ],
        "pattern": "^(.*)$"
      }
    },
    "type": {
      "$id": "#/properties/type",
      "type": "string",
      "title": "The Type",
      "default": "",
      "examples": [
        "journal-article"
      ],
      "pattern": "^(.*)$"
    },
    "license": {
      "$id": "#/properties/license",
      "type": "array",
      "title": "The License",
      "items": {
        "$id": "#/properties/license/items",
        "type": "object",
        "title": "The Items",
        "required": [
          "url",
          "date-time",
          "content-version",
          "delay-in-days"
        ],
        "properties": {
          "url": {
            "$id": "#/properties/license/items/properties/url",
            "type": "string",
            "title": "The Url",
            "default": "",
            "examples": [
              "http://www.elsevier.com/tdm/userlicense/1.0/"
            ],
            "pattern": "^(.*)$"
          },
          "date-time": {
            "$id": "#/properties/license/items/properties/date-time",
            "type": "string",
            "title": "The Date-time",
            "default": "",
            "examples": [
              "2011-07-01T00:00:00Z"
            ],
            "pattern": "^(.*)$"
          },
          "content-version": {
            "$id": "#/properties/license/items/properties/content-version",
            "type": "string",
            "title": "The Content-version",
            "default": "",
            "examples": [
              "tdm"
            ],
            "pattern": "^(.*)$"
          },
          "delay-in-days": {
            "$id": "#/properties/license/items/properties/delay-in-days",
            "type": "integer",
            "title": "The Delay-in-days",
            "default": 0,
            "examples": [
              0
            ]
          }
        }
      }
    },
    "instances": {
      "$id": "#/properties/instances",
      "type": "array",
      "title": "The Instances",
      "items": {
        "$id": "#/properties/instances/items",
        "type": "object",
        "title": "The Items",
        "required": [
          "url",
          "access-rights",
          "provenance"
        ],
        "properties": {
          "url": {
            "$id": "#/properties/instances/items/properties/url",
            "type": "string",
            "title": "The Url",
            "default": "",
            "examples": [
              "http://unkonwonInstance.org"
            ],
            "pattern": "^(.*)$"
          },
          "access-rights": {
            "$id": "#/properties/instances/items/properties/access-rights",
            "type": "string",
            "title": "The Access-rights",
            "default": "",
            "examples": [
              "UNKNOWN"
            ],
            "pattern": "^(.*)$"
          },
          "provenance": {
            "$id": "#/properties/instances/items/properties/provenance",
            "type": "string",
            "title": "The Provenance",
            "default": "",
            "examples": [
              "CrossRef"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "published-online": {
      "$id": "#/properties/published-online",
      "type": "string",
      "title": "The Published-online",
      "default": "",
      "examples": [
        "2016-08-01"
      ],
      "pattern": "^(.*)$"
    },
    "published-print": {
      "$id": "#/properties/published-print",
      "type": "string",
      "title": "The Published-print",
      "default": "",
      "examples": [
        "2016-07-01"
      ],
      "pattern": "^(.*)$"
    },
    "accepted": {
      "$id": "#/properties/accepted",
      "type": "string",
      "title": "The Accepted",
      "default": "",
      "examples": [
        "2016-01-01"
      ],
      "pattern": "^(.*)$"
    },
    "publisher": {
      "$id": "#/properties/publisher",
      "type": "string",
      "title": "The Publisher",
      "default": "",
      "examples": [
        "Publisher Name"
      ],
      "pattern": "^(.*)$"
    },
    "doi": {
      "$id": "#/properties/doi",
      "type": "string",
      "title": "The Doi",
      "default": "",
      "examples": [
        "10.1016/j.ffhfhgfhf"
      ],
      "pattern": "^(.*)$"
    },
    "doi-url": {
      "$id": "#/properties/doi-url",
      "type": "string",
      "title": "The Doi-url",
      "default": "",
      "examples": [
        "http://dx.doi.org/10.1016/j.ffhfhgfhf"
      ],
      "pattern": "^(.*)$"
    },
    "issn": {
      "$id": "#/properties/issn",
      "type": "array",
      "title": "The Issn",
      "items": {
        "$id": "#/properties/issn/items",
        "type": "object",
        "title": "The Items",
        "required": [
          "type",
          "value"
        ],
        "properties": {
          "type": {
            "$id": "#/properties/issn/items/properties/type",
            "type": "string",
            "title": "The Type",
            "default": "",
            "examples": [
              "print"
            ],
            "pattern": "^(.*)$"
          },
          "value": {
            "$id": "#/properties/issn/items/properties/value",
            "type": "string",
            "title": "The Value",
            "default": "",
            "examples": [
              "01234-5678"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "collected-from": {
      "$id": "#/properties/collected-from",
      "type": "array",
      "title": "The Collected-from",
      "items": {
        "$id": "#/properties/collected-from/items",
        "type": "string",
        "title": "The Items",
        "default": "",
        "examples": [
          "CrossRef",
          "MAG",
          "Unpaywall",
          "ORCID"
        ],
        "pattern": "^(.*)$"
      }
    }
  }
}

=== sandrolabruzzo/doiBoost/python/schema/doiBoostSample.json
{
  "title":"My Title",
  "authors":[
    {
      "given":"Marco",
      "family":"Rossi",
      "fullname":"Marco Rossi",
      "identifiers":[
        {
          "schema":"ORCID",
          "value":"https://..../0000-0002-3337-2025",
          "provenance":"ORCID"
        },
        {
          "schema":"URL",
          "value":"https://.../1278293695",
          "provenance":"MAG"
        }
      ],
      "affiliations":[
        {
          "value":"My Affiliation Name",
          "official-page":"www.affiliation.org",
          "identifiers":[
            {
              "schema":"grid.ac",
              "value":"https://.../grid.12345.a"
            },
            {
              "schema":"microsoftID",
              "value":"https://.../4213412341"
            },
            {
              "schema":"wikipedia",
              "value":"https:///wiki/my_affiliation"
            }
          ],
          "provenance":"MAG"
        }
      ]
    },
    {
      "given":"Giuseppe",
      "family":"Trovato",
      "fullname":"Giuseppe Trovato",
      "identifiers":[

      ],
      "affiliations":[

      ]
    }
  ],
  "issued":"2016-07-01",
  "abstract":[
    {
      "value":"Abstract Text",
      "provenance":"MAG"
    },
    {
      "value":"Abstract Text",
      "provenance":"CrossRef"
    }
  ],
  "subject":[
    "Agronomy and Crop Science",
    "Forestry"
  ],
  "type":"journal-article",
  "license":[
    {
      "url":"http://www.elsevier.com/tdm/userlicense/1.0/",
      "date-time":"2011-07-01T00:00:00Z",
      "content-version":"tdm",
      "delay-in-days":0
    }
  ],
  "instances":[
    {
      "url":"http://unkonwonInstance.org",
      "access-rights":"UNKNOWN",
      "provenance":"CrossRef"
    },
    {
      "url":"http://openAccessInstance.org",
      "access-rights":"OPEN",
      "provenance":"Unpaywall"
    }
  ],
  "published-online":"2016-08-01",
  "published-print":"2016-07-01",
  "accepted":"2016-01-01",
  "publisher":"Publisher Name",
  "doi":"10.1016/j.ffhfhgfhf",
  "doi-url":"http://dx.doi.org/10.1016/j.ffhfhgfhf",
  "issn":[
    {
      "type":"print",
      "value":"01234-5678"
    }
  ],
  "collected-from":[
    "CrossRef",
    "MAG",
    "Unpaywall",
    "ORCID"
  ]
}
